version: '3.8'

services:
  redis-server:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5

  order-service:
    depends_on:
      redis-server:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis-server
      - SPRING_REDIS_PORT=6379

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"