apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
    template:
      metadata:
        labels:
          app: order-service
      spec:
        containers:
          - name: order-service
            image: kemblekaran/order-service:latest
            ports:
              - containerPort: 8080
            env:
              - name: SPRING_REDIS_HOST
                value: redis